wandb:
    entity: r-ap

experiment:
    project: "muse-vae"
    name: "vqgan-training"
    output_dir: "output"
    max_train_examples: 30000 # total number of imagenet examples
    max_eval_examples: 1000
    save_every: 6300
    eval_every: 1000
    generate_every: 200
    log_every: 100
    log_grad_norm_every: 500
    resume_from_checkpoint: False
    resume_lr_scheduler: True

model:
    vq_model:
        type: "taming_vqgan"
        pretrained: "openMUSE/vqgan-f16-8192-laion"
    gradient_checkpointing: True
    enable_xformers_memory_efficient_attention: False


dataset:
    preprocessing:
        max_seq_length: 16
        resolution: 256
discriminator:
    dim: 64
    channels: 3
    groups: 32
    init_kernel_size: 5
    kernel_size: 3
    act: "silu"
    discr_layers: 4
optimizer:
    name: adamw
    params: # default adamw params
        learning_rate: 1e-4
        scale_lr: False # scale learning rate by total batch size
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.01
        epsilon: 1e-8
        discr_learning_rate: 1e-4


lr_scheduler:
    scheduler: "constant_with_warmup"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 100


training:
    gradient_accumulation_steps: 2
    batch_size: 4
    mixed_precision: "no"
    enable_tf32: True
    use_ema: False
    seed: 1337
    max_train_steps: 20000
    overfit_one_batch: False
    cond_dropout_prob: 0.1
    min_masking_rate: 0.0
    label_smoothing: 0.0
    max_grad_norm: null
    guidance_scale: 2.0
    generation_timesteps: 8
    # related to vae code sampling
    use_soft_code_target: False
    use_stochastic_code: False
    soft_code_temp: 1.0
    timm_discriminator_backend: "vgg19"
    timm_disc_layers: "features|pre_logits|head"
    timm_discr_offset: 0
    vae_loss: "l2"
    num_validation_log: 4
    discriminator_warmup: 100
